.TH "app/src/activityitem.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/activityitem.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./lib/activityitem\&.h'\fP
.br
\fR#include <QPainter>\fP
.br
\fR#include <QTextDocument>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
