.TH "app/src/activity.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/activity.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./lib/activity\&.h'\fP
.br
\fR#include <QVariantMap>\fP
.br
\fR#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
