.TH "app/lib/activity.h" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/activity.h
.SH SYNOPSIS
.br
.PP
\fC#include 'serializable\&.h'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QTime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
