.TH "Activity" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Activity
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <activity\&.h>\fP
.PP
Inherits \fBSerializable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActivity\fP ()"
.br
.ti -1c
.RI "\fBActivity\fP (QString mActivityText, QTime mStart, QTime mEnd)"
.br
.ti -1c
.RI "\fB~Activity\fP () override"
.br
.ti -1c
.RI "QString \fBactivityText\fP () const"
.br
.ti -1c
.RI "QTime \fBstart\fP () const"
.br
.ti -1c
.RI "QTime \fBend\fP () const"
.br
.ti -1c
.RI "QVariant \fBtoVariant\fP () const override"
.br
.ti -1c
.RI "void \fBfromVariant\fP (const QVariant &variant) override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString \fBm_activityText\fP"
.br
.ti -1c
.RI "QTime \fBm_start\fP"
.br
.ti -1c
.RI "QTime \fBm_end\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Private Member Functions inherited from \fBSerializable\fP
.in +1c
.ti -1c
.RI "virtual \fB~Serializable\fP ()=default"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Activity::Activity ()"

.SS "Activity::Activity (QString mActivityText, QTime mStart, QTime mEnd)"

.SS "Activity::~Activity ()\fR [override]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QString Activity::activityText () const\fR [inline]\fP"

.SS "QTime Activity::end () const\fR [inline]\fP"

.SS "void Activity::fromVariant (const QVariant & variant)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SS "QTime Activity::start () const\fR [inline]\fP"

.SS "QVariant Activity::toVariant () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QString Activity::m_activityText\fR [private]\fP"

.SS "QTime Activity::m_end\fR [private]\fP"

.SS "QTime Activity::m_start\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
