.TH "app/lib/activityitem.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/activityitem.h
.SH SYNOPSIS
.br
.PP
\fR#include 'activity\&.h'\fP
.br
\fR#include <QGraphicsItem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivityItem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
