.TH "app/lib/calendar.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/calendar.h
.SH SYNOPSIS
.br
.PP
\fR#include 'serializable\&.h'\fP
.br
\fR#include <QDate>\fP
.br
\fR#include <QMap>\fP
.br
\fR#include <QPair>\fP
.br
\fR#include <QTime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalendar\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
