.TH "app/lib/card.h" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/card.h
.SH SYNOPSIS
.br
.PP
\fC#include 'serializable\&.h'\fP
.br
\fC#include <QJsonObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCard\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDifficulty\fP { \fBEASY\fP = 0, \fBMEDIUM\fP, \fBHARD\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDifficulty\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEASY \fP\fP
.TP
\fB\fIMEDIUM \fP\fP
.TP
\fB\fIHARD \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
