.TH "Card" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <card\&.h>\fP
.PP
Inherits \fBSerializable\fP\&.
.PP
Inherited by \fBImageCard\fP, and \fBPlainCard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCard\fP ()"
.br
.ti -1c
.RI "\fBCard\fP (QString mQuestionText, QString mAnswerText, \fBDifficulty\fP mQuestionDifficulty)"
.br
.ti -1c
.RI "\fBCard\fP (const \fBCard\fP &card)"
.br
.ti -1c
.RI "\fB~Card\fP () override"
.br
.ti -1c
.RI "QString \fBquestionText\fP () const"
.br
.ti -1c
.RI "QString \fBquestionAnswer\fP () const"
.br
.ti -1c
.RI "\fBDifficulty\fP \fBquestionDifficulty\fP () const"
.br
.ti -1c
.RI "QVariant \fBtoVariant\fP () const override"
.br
.ti -1c
.RI "void \fBfromVariant\fP (const QVariant &variant) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QString \fBm_questionText\fP"
.br
.ti -1c
.RI "QString \fBm_answerText\fP"
.br
.ti -1c
.RI "\fBDifficulty\fP \fBm_questionDifficulty\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Card::Card ()"

.SS "Card::Card (QString mQuestionText, QString mAnswerText, \fBDifficulty\fP mQuestionDifficulty)"

.SS "Card::Card (const \fBCard\fP & card)"

.SS "Card::~Card ()\fC [override]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Card::fromVariant (const QVariant & variant)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SS "QString Card::questionAnswer () const\fC [inline]\fP"

.SS "\fBDifficulty\fP Card::questionDifficulty () const\fC [inline]\fP"

.SS "QString Card::questionText () const\fC [inline]\fP"

.SS "QVariant Card::toVariant () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QString Card::m_answerText\fC [protected]\fP"

.SS "\fBDifficulty\fP Card::m_questionDifficulty\fC [protected]\fP"

.SS "QString Card::m_questionText\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
