.TH "app/src/createdeckdialog.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/createdeckdialog.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./lib/createdeckdialog\&.h'\fP
.br
\fR#include 'ui_createdeckdialog\&.h'\fP
.br
\fR#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
