.TH "app/lib/createdeckwindow.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/createdeckwindow.h
.SH SYNOPSIS
.br
.PP
\fR#include 'deck\&.h'\fP
.br
\fR#include 'user\&.h'\fP
.br
\fR#include <QButtonGroup>\fP
.br
\fR#include <QLabel>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreateDeckWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
