.TH "app/src/createdeckdialog.cpp" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/createdeckdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./lib/createdeckdialog\&.h'\fP
.br
\fC#include 'ui_createdeckdialog\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
