.TH "app/lib/createdeckdialog.h" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/createdeckdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include 'deck\&.h'\fP
.br
\fC#include <QButtonGroup>\fP
.br
\fC#include <QDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCreateDeckDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
