.TH "app/lib/deckstats.h" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/deckstats.h
.SH SYNOPSIS
.br
.PP
\fC#include 'card\&.h'\fP
.br
\fC#include 'deck\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include <QDate>\fP
.br
\fC#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeckStats\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
