.TH "Deck" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Deck
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deck\&.h>\fP
.PP
Inherits \fBSerializable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeck\fP ()"
.br
.ti -1c
.RI "\fBDeck\fP (QString \fBname\fP, const \fBUser\fP &\fBuser\fP, \fBPrivacy\fP \fBprivacy\fP)"
.br
.ti -1c
.RI "\fBDeck\fP (const \fBDeck\fP &deck)"
.br
.ti -1c
.RI "\fB~Deck\fP () override"
.br
.ti -1c
.RI "unsigned int \fBdeckId\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QVector< \fBCard\fP * > \fBcards\fP ()"
.br
.ti -1c
.RI "\fBPrivacy\fP \fBprivacy\fP () const"
.br
.ti -1c
.RI "\fBUser\fP \fBuser\fP () const"
.br
.ti -1c
.RI "void \fBaddCard\fP (\fBCard\fP *card)"
.br
.ti -1c
.RI "void \fBsetId\fP (uint64_t id)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBDeck\fP &deck)"
.br
.ti -1c
.RI "QVariant \fBtoVariant\fP () const override"
.br
.ti -1c
.RI "void \fBfromVariant\fP (const QVariant &variant) override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBm_deckId\fP"
.br
.ti -1c
.RI "QString \fBm_name\fP"
.br
.ti -1c
.RI "QVector< \fBCard\fP * > \fBm_cards\fP"
.br
.ti -1c
.RI "\fBPrivacy\fP \fBm_privacy\fP"
.br
.ti -1c
.RI "\fBUser\fP \fBm_user\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Deck::Deck ()"

.SS "Deck::Deck (QString name, const \fBUser\fP & user, \fBPrivacy\fP privacy)"

.SS "Deck::Deck (const \fBDeck\fP & deck)"

.SS "Deck::~Deck ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Deck::addCard (\fBCard\fP * card)"

.SS "QVector<\fBCard\fP *> Deck::cards ()\fC [inline]\fP"

.SS "unsigned int Deck::deckId () const\fC [inline]\fP"

.SS "void Deck::fromVariant (const QVariant & variant)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SS "QString Deck::name () const\fC [inline]\fP"

.SS "bool Deck::operator== (const \fBDeck\fP & deck)"

.SS "\fBPrivacy\fP Deck::privacy () const\fC [inline]\fP"

.SS "void Deck::setId (uint64_t id)"

.SS "QVariant Deck::toVariant () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SS "\fBUser\fP Deck::user () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "QVector<\fBCard\fP *> Deck::m_cards\fC [private]\fP"

.SS "unsigned Deck::m_deckId\fC [private]\fP"

.SS "QString Deck::m_name\fC [private]\fP"

.SS "\fBPrivacy\fP Deck::m_privacy\fC [private]\fP"

.SS "\fBUser\fP Deck::m_user\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
