.TH "app/src/deckpreviewwindow.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/deckpreviewwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'lib/deckpreviewwindow\&.h'\fP
.br
\fR#include 'lib/jsonserializer\&.h'\fP
.br
\fR#include 'lib/servercommunicator\&.h'\fP
.br
\fR#include 'ui_deckpreviewwindow\&.h'\fP
.br
\fR#include <QMessageBox>\fP
.br
\fR#include <QTcpServer>\fP
.br
\fR#include <QTcpSocket>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
