.TH "app/lib/deckstats.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/deckstats.h
.SH SYNOPSIS
.br
.PP
\fR#include 'card\&.h'\fP
.br
\fR#include 'deck\&.h'\fP
.br
\fR#include 'user\&.h'\fP
.br
\fR#include <QDate>\fP
.br
\fR#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeckStats\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
