.TH "app/src/deck.cpp" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/deck.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./lib/deck\&.h'\fP
.br
\fC#include <QJsonArray>\fP
.br
\fC#include <QRandomGenerator>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
