.TH "app/lib/deck.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/deck.h
.SH SYNOPSIS
.br
.PP
\fR#include 'card\&.h'\fP
.br
\fR#include 'user\&.h'\fP
.br
\fR#include <QImage>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeck\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPrivacy\fP { \fBPRIVATE\fP, \fBPUBLIC\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPrivacy\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPRIVATE \fP\fP
.TP
\fB\fIPUBLIC \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
