.TH "app/lib/imagecard.h" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/imagecard.h
.SH SYNOPSIS
.br
.PP
\fC#include 'card\&.h'\fP
.br
\fC#include <QImage>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImageCard\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
