.TH "app/lib/jsonserializer.h" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/jsonserializer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'serializer\&.h'\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QString>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJSONSerializer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
