.TH "app/src/jsonserializer.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/jsonserializer.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./lib/jsonserializer\&.h'\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QJsonDocument>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
