.TH "JSONSerializer" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSONSerializer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsonserializer\&.h>\fP
.PP
Inherits \fBSerializer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSONSerializer\fP ()"
.br
.ti -1c
.RI "void \fBsave\fP (const \fBSerializable\fP &serializable, const QString &filepath, const QString &rootname='') override"
.br
.ti -1c
.RI "void \fBload\fP (\fBSerializable\fP &serializable, const QString &filepath) override"
.br
.ti -1c
.RI "QJsonDocument \fBcreateJson\fP (const \fBSerializable\fP &serializable)"
.br
.ti -1c
.RI "void \fBloadJson\fP (\fBSerializable\fP &serializable, QJsonDocument &jsonDeck)"
.br
.in -1c

Public Member Functions inherited from \fBSerializer\fP
.in +1c
.ti -1c
.RI "virtual \fB~Serializer\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBsave\fP (const \fBSerializable\fP &serializable, const QString &filepath, const QString &rootname='')=0"
.br
.ti -1c
.RI "virtual void \fBload\fP (\fBSerializable\fP &serializable, const QString &filepath)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JSONSerializer::JSONSerializer ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QJsonDocument JSONSerializer::createJson (const \fBSerializable\fP & serializable)"

.SS "void JSONSerializer::load (\fBSerializable\fP & serializable, const QString & filepath)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializer\fP\&.
.SS "void JSONSerializer::loadJson (\fBSerializable\fP & serializable, QJsonDocument & jsonDeck)"

.SS "void JSONSerializer::save (const \fBSerializable\fP & serializable, const QString & filepath, const QString & rootname = \fC''\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
