.TH "app/src/logindialog.cpp" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/logindialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./lib/logindialog\&.h'\fP
.br
\fC#include 'ui_logindialog\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBLOGIN\fP = (0), \fBREGISTER\fP = (1) }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILOGIN \fP\fP
.TP
\fB\fIREGISTER \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
