.TH "app/src/mainwindow.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'lib/mainwindow\&.h'\fP
.br
\fR#include 'lib/createdeckdialog\&.h'\fP
.br
\fR#include 'lib/createdeckwindow\&.h'\fP
.br
\fR#include 'lib/deckpreviewwindow\&.h'\fP
.br
\fR#include 'lib/jsonserializer\&.h'\fP
.br
\fR#include 'lib/logindialog\&.h'\fP
.br
\fR#include 'lib/scheduleitem\&.h'\fP
.br
\fR#include 'lib/servercommunicator\&.h'\fP
.br
\fR#include 'lib/studysessionwindow\&.h'\fP
.br
\fR#include 'lib/user\&.h'\fP
.br
\fR#include 'ui_mainwindow\&.h'\fP
.br
\fR#include <QCryptographicHash>\fP
.br
\fR#include <QJsonDocument>\fP
.br
\fR#include <QJsonObject>\fP
.br
\fR#include <QTcpServer>\fP
.br
\fR#include <QTcpSocket>\fP
.br
\fR#include <QTextStream>\fP
.br
\fR#include <QApplication>\fP
.br
\fR#include <QCheckBox>\fP
.br
\fR#include <QDirIterator>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QFileDialog>\fP
.br
\fR#include <QMessageBox>\fP
.br
\fR#include <QStandardPaths>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPage\fP { \fBLIBRARY\fP = 0, \fBTODO\fP, \fBPLANER\fP, \fBCALENDAR\fP, \fBSTATS\fP, \fBSETTINGS\fP, \fBHELP\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPage\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILIBRARY \fP\fP
.TP
\fB\fITODO \fP\fP
.TP
\fB\fIPLANER \fP\fP
.TP
\fB\fICALENDAR \fP\fP
.TP
\fB\fISTATS \fP\fP
.TP
\fB\fISETTINGS \fP\fP
.TP
\fB\fIHELP \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
