.TH "app/lib/mainwindow.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fR#include 'lib/calendar\&.h'\fP
.br
\fR#include 'lib/deckstats\&.h'\fP
.br
\fR#include 'lib/planner\&.h'\fP
.br
\fR#include 'lib/plannerscene\&.h'\fP
.br
\fR#include 'lib/todolist\&.h'\fP
.br
\fR#include 'settings\&.h'\fP
.br
\fR#include 'user\&.h'\fP
.br
\fR#include <QListWidgetItem>\fP
.br
\fR#include <QWidget>\fP
.br
\fR#include <QCoreApplication>\fP
.br
\fR#include <QDir>\fP
.br
\fR#include <QStandardPaths>\fP
.br
\fR#include <QTableWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
