.TH "PlainCard" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlainCard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plaincard\&.h>\fP
.PP
Inherits \fBCard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlainCard\fP ()"
.br
.ti -1c
.RI "\fBPlainCard\fP (QString \fBquestionText\fP, QString answerText, \fBDifficulty\fP \fBquestionDifficulty\fP)"
.br
.ti -1c
.RI "\fB~PlainCard\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlainCard::PlainCard ()"

.SS "PlainCard::PlainCard (QString questionText, QString answerText, \fBDifficulty\fP questionDifficulty)"

.SS "PlainCard::~PlainCard ()\fC [override]\fP, \fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
