.TH "app/src/plaincard.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/plaincard.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./lib/plaincard\&.h'\fP
.br
\fR#include '\&.\&./lib/card\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
