.TH "app/lib/plaincard.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/plaincard.h
.SH SYNOPSIS
.br
.PP
\fR#include 'card\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlainCard\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
