.TH "app/lib/planner.h" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/planner.h
.SH SYNOPSIS
.br
.PP
\fC#include 'activity\&.h'\fP
.br
\fC#include 'serializable\&.h'\fP
.br
\fC#include <QMap>\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlanner\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDay\fP { \fBMONDAY\fP = 0, \fBTUESDAY\fP, \fBWEDNESDAY\fP, \fBTHURSDAY\fP, \fBFRIDAY\fP, \fBSATURDAY\fP, \fBSUNDAY\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDay\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMONDAY \fP\fP
.TP
\fB\fITUESDAY \fP\fP
.TP
\fB\fIWEDNESDAY \fP\fP
.TP
\fB\fITHURSDAY \fP\fP
.TP
\fB\fIFRIDAY \fP\fP
.TP
\fB\fISATURDAY \fP\fP
.TP
\fB\fISUNDAY \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
