.TH "Planner" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Planner
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <planner\&.h>\fP
.PP
Inherits \fBSerializable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlanner\fP ()"
.br
.ti -1c
.RI "\fB~Planner\fP () override"
.br
.ti -1c
.RI "QVariant \fBtoVariant\fP () const override"
.br
.ti -1c
.RI "void \fBfromVariant\fP (const QVariant &variant) override"
.br
.ti -1c
.RI "void \fBaddActivity\fP (\fBDay\fP day, \fBActivity\fP activity)"
.br
.ti -1c
.RI "void \fBdeleteAll\fP ()"
.br
.ti -1c
.RI "QMap< \fBDay\fP, QVector< \fBActivity\fP > > \fBactivities\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDay\fP \fBdayFromString\fP (QString dayString)"
.br
.ti -1c
.RI "static QString \fBdayToString\fP (\fBDay\fP day)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QMap< \fBDay\fP, QVector< \fBActivity\fP > > \fBm_activities\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Planner::Planner ()"

.SS "Planner::~Planner ()\fC [override]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QMap<\fBDay\fP, QVector<\fBActivity\fP> > Planner::activities () const\fC [inline]\fP"

.SS "void Planner::addActivity (\fBDay\fP day, \fBActivity\fP activity)"

.SS "\fBDay\fP Planner::dayFromString (QString dayString)\fC [static]\fP"

.SS "QString Planner::dayToString (\fBDay\fP day)\fC [static]\fP"

.SS "void Planner::deleteAll ()"

.SS "void Planner::fromVariant (const QVariant & variant)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SS "QVariant Planner::toVariant () const\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBSerializable\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QMap<\fBDay\fP, QVector<\fBActivity\fP> > Planner::m_activities\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
