.TH "app/lib/plannerscene.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/plannerscene.h
.SH SYNOPSIS
.br
.PP
\fR#include 'activityitem\&.h'\fP
.br
\fR#include <QGraphicsScene>\fP
.br
\fR#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlannerScene\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
