.TH "ScheduleItem" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScheduleItem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scheduleitem\&.h>\fP
.PP
Inherits QGraphicsItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScheduleItem\fP ()"
.br
.ti -1c
.RI "QRectF \fBboundingRect\fP () const override"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) override"
.br
.ti -1c
.RI "unsigned \fBwidth\fP () const"
.br
.ti -1c
.RI "unsigned \fBheight\fP () const"
.br
.ti -1c
.RI "void \fBsetWidth\fP (unsigned \fBwidth\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBm_width\fP = 180"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ScheduleItem::ScheduleItem ()\fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QRectF ScheduleItem::boundingRect () const\fR [override]\fP"

.SS "unsigned ScheduleItem::height () const\fR [inline]\fP"

.SS "void ScheduleItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)\fR [override]\fP"

.SS "void ScheduleItem::setWidth (unsigned width)"

.SS "unsigned ScheduleItem::width () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned ScheduleItem::m_width = 180\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
