.TH "app/src/scheduleitem.cpp" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/scheduleitem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./lib/scheduleitem\&.h'\fP
.br
\fC#include <QPainter>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
