.TH "app/lib/serializable.h" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/serializable.h
.SH SYNOPSIS
.br
.PP
\fC#include <QVariant>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSerializable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
