.TH "Serializable" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serializable
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <serializable\&.h>\fP
.PP
Inherited by \fBActivity\fP\fR [private]\fP, \fBCalendar\fP, \fBCard\fP, \fBDeck\fP, \fBDeckStats\fP, \fBPlanner\fP, \fBToDoList\fP, and \fBUser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Serializable\fP ()=default"
.br
.ti -1c
.RI "virtual QVariant \fBtoVariant\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBfromVariant\fP (const QVariant &variant)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Serializable::~Serializable ()\fR [virtual]\fP, \fR [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Serializable::fromVariant (const QVariant & variant)\fR [pure virtual]\fP"

.PP
Implemented in \fBActivity\fP, \fBCalendar\fP, \fBCard\fP, \fBDeck\fP, \fBDeckStats\fP, \fBPlanner\fP, \fBToDoList\fP, and \fBUser\fP\&.
.SS "virtual QVariant Serializable::toVariant () const\fR [pure virtual]\fP"

.PP
Implemented in \fBActivity\fP, \fBCalendar\fP, \fBCard\fP, \fBDeck\fP, \fBDeckStats\fP, \fBPlanner\fP, \fBToDoList\fP, and \fBUser\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
