.TH "Serializer" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serializer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serializer\&.h>\fP
.PP
Inherited by \fBJSONSerializer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Serializer\fP ()=default"
.br
.ti -1c
.RI "virtual void \fBsave\fP (const \fBSerializable\fP &serializable, const QString &filepath, const QString &rootname='')=0"
.br
.ti -1c
.RI "virtual void \fBload\fP (\fBSerializable\fP &serializable, const QString &filepath)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Serializer::~Serializer ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Serializer::load (\fBSerializable\fP & serializable, const QString & filepath)\fC [pure virtual]\fP"

.PP
Implemented in \fBJSONSerializer\fP\&.
.SS "virtual void Serializer::save (const \fBSerializable\fP & serializable, const QString & filepath, const QString & rootname = \fC''\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBJSONSerializer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
