.TH "ServerCommunicator" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerCommunicator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <servercommunicator\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerCommunicator\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QJsonObject \fBsendRequest\fP (const QJsonDocument &request)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QTcpSocket * \fBsocket\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ServerCommunicator::ServerCommunicator (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QJsonObject ServerCommunicator::sendRequest (const QJsonDocument & request)"

.SH "Member Data Documentation"
.PP 
.SS "QTcpSocket* ServerCommunicator::socket\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
