.TH "app/src/servercommunicator.cpp" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/servercommunicator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./lib/servercommunicator\&.h'\fP
.br
\fC#include <QTextStream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
