.TH "app/src/settings.cpp" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/settings.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include '\&.\&./lib/settings\&.h'\fP
.br
\fC#include <QTranslator>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
