.TH "app/lib/settings.h" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/settings.h
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLanguage\fP { \fBSERBIAN\fP = 0, \fBENGLISH\fP }"
.br
.ti -1c
.RI "enum \fBTheme\fP { \fBBLUE\fP = 0, \fBORANGE\fP, \fBDARK\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLanguage\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISERBIAN \fP\fP
.TP
\fB\fIENGLISH \fP\fP
.SS "enum \fBTheme\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBLUE \fP\fP
.TP
\fB\fIORANGE \fP\fP
.TP
\fB\fIDARK \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
