.TH "app/src/studysession.cpp" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/studysession.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./lib/studysession\&.h'\fP
.br
\fC#include '\&.\&./lib/jsonserializer\&.h'\fP
.br
\fC#include '\&.\&./lib/servercommunicator\&.h'\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QRandomGenerator>\fP
.br
\fC#include <QTcpServer>\fP
.br
\fC#include <QTcpSocket>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <numeric>\fP
.br
\fC#include <random>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
