.TH "app/src/studysessionwindow.cpp" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/studysessionwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib/studysessionwindow\&.h'\fP
.br
\fC#include 'lib/jsonserializer\&.h'\fP
.br
\fC#include 'lib/serializer\&.h'\fP
.br
\fC#include 'lib/servercommunicator\&.h'\fP
.br
\fC#include 'ui_studysessionwindow\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QTcpServer>\fP
.br
\fC#include <QTcpSocket>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
