.TH "StudySessionWindow" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StudySessionWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <studysessionwindow\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBcloseWhiteboard\fP ()"
.br
.ti -1c
.RI "void \fBclearWhiteboard\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStudySessionWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBStudySessionWindow\fP (\fBStudySession\fP *\fBsession\fP, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~StudySessionWindow\fP () override"
.br
.ti -1c
.RI "\fBStudySession\fP * \fBsession\fP () const"
.br
.ti -1c
.RI "void \fBevaluate\fP (int grade)"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_pushButton_flip_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_skip_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_bad_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_mid_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_good_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_whiteboard_clicked\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetDifficultyColor\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::StudySessionWindow * \fBui\fP"
.br
.ti -1c
.RI "\fBStudySession\fP * \fBm_session\fP"
.br
.ti -1c
.RI "\fBWhiteboardWindow\fP * \fBm_whiteboard\fP = nullptr"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StudySessionWindow::StudySessionWindow (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "StudySessionWindow::StudySessionWindow (\fBStudySession\fP * session, QWidget * parent = \fCnullptr\fP)"

.SS "StudySessionWindow::~StudySessionWindow ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void StudySessionWindow::clearWhiteboard ()\fC [slot]\fP"

.SS "void StudySessionWindow::closeWhiteboard ()\fC [slot]\fP"

.SS "void StudySessionWindow::evaluate (int grade)"

.SS "void StudySessionWindow::on_pushButton_bad_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "void StudySessionWindow::on_pushButton_flip_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "void StudySessionWindow::on_pushButton_good_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "void StudySessionWindow::on_pushButton_mid_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "void StudySessionWindow::on_pushButton_skip_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "void StudySessionWindow::on_pushButton_whiteboard_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "\fBStudySession\fP * StudySessionWindow::session () const\fC [inline]\fP"

.SS "void StudySessionWindow::setDifficultyColor ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBStudySession\fP* StudySessionWindow::m_session\fC [private]\fP"

.SS "\fBWhiteboardWindow\fP* StudySessionWindow::m_whiteboard = nullptr\fC [private]\fP"

.SS "Ui::StudySessionWindow* StudySessionWindow::ui\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
