.TH "app/lib/studysession.h" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/studysession.h
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'card\&.h'\fP
.br
\fC#include 'deck\&.h'\fP
.br
\fC#include 'deckstats\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStudySession\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
