.TH "StudySession" 3 "Tue Jan 9 2024" "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StudySession
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <studysession\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStudySession\fP ()"
.br
.ti -1c
.RI "\fBStudySession\fP (const \fBUser\fP &\fBuser\fP, \fBDeck\fP *\fBdeck\fP)"
.br
.ti -1c
.RI "\fBStudySession\fP (const \fBStudySession\fP &session)"
.br
.ti -1c
.RI "\fB~StudySession\fP ()"
.br
.ti -1c
.RI "\fBUser\fP \fBuser\fP () const"
.br
.ti -1c
.RI "\fBDeck\fP * \fBdeck\fP ()"
.br
.ti -1c
.RI "unsigned \fBcurrentCardIndex\fP () const"
.br
.ti -1c
.RI "time_t \fBtimeStarted\fP () const"
.br
.ti -1c
.RI "time_t \fBtimeEnded\fP () const"
.br
.ti -1c
.RI "QVector< unsigned > \fBcardSequence\fP ()"
.br
.ti -1c
.RI "bool \fBanswerShowed\fP ()"
.br
.ti -1c
.RI "\fBDeckStats\fP * \fBdeckStats\fP ()"
.br
.ti -1c
.RI "void \fBstartSession\fP ()"
.br
.ti -1c
.RI "void \fBendSession\fP ()"
.br
.ti -1c
.RI "void \fBchooseCardSequence\fP (unsigned numCards)"
.br
.ti -1c
.RI "void \fBnextCard\fP ()"
.br
.ti -1c
.RI "\fBCard\fP \fBgetCurrentCard\fP ()"
.br
.ti -1c
.RI "void \fBflipCard\fP ()"
.br
.ti -1c
.RI "bool \fBhasNextCard\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUser\fP \fBm_user\fP"
.br
.ti -1c
.RI "\fBDeck\fP * \fBm_deck\fP"
.br
.ti -1c
.RI "time_t \fBm_timeStarted\fP"
.br
.ti -1c
.RI "time_t \fBm_timeEnded\fP"
.br
.ti -1c
.RI "QVector< unsigned > \fBm_cardSequence\fP"
.br
.ti -1c
.RI "unsigned \fBm_currentCardIndex\fP"
.br
.ti -1c
.RI "bool \fBm_answerShowed\fP = false"
.br
.ti -1c
.RI "\fBDeckStats\fP * \fBm_deckStats\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StudySession::StudySession ()"

.SS "StudySession::StudySession (const \fBUser\fP & user, \fBDeck\fP * deck)"

.SS "StudySession::StudySession (const \fBStudySession\fP & session)"

.SS "StudySession::~StudySession ()"

.SH "Member Function Documentation"
.PP 
.SS "bool StudySession::answerShowed ()\fC [inline]\fP"

.SS "QVector<unsigned> StudySession::cardSequence ()\fC [inline]\fP"

.SS "void StudySession::chooseCardSequence (unsigned numCards)"

.SS "unsigned StudySession::currentCardIndex () const\fC [inline]\fP"

.SS "\fBDeck\fP* StudySession::deck ()\fC [inline]\fP"

.SS "\fBDeckStats\fP* StudySession::deckStats ()\fC [inline]\fP"

.SS "void StudySession::endSession ()"

.SS "void StudySession::flipCard ()"

.SS "\fBCard\fP StudySession::getCurrentCard ()"

.SS "bool StudySession::hasNextCard ()"

.SS "void StudySession::nextCard ()"

.SS "void StudySession::startSession ()"

.SS "time_t StudySession::timeEnded () const\fC [inline]\fP"

.SS "time_t StudySession::timeStarted () const\fC [inline]\fP"

.SS "\fBUser\fP StudySession::user () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool StudySession::m_answerShowed = false\fC [private]\fP"

.SS "QVector<unsigned> StudySession::m_cardSequence\fC [private]\fP"

.SS "unsigned StudySession::m_currentCardIndex\fC [private]\fP"

.SS "\fBDeck\fP* StudySession::m_deck\fC [private]\fP"

.SS "\fBDeckStats\fP* StudySession::m_deckStats\fC [private]\fP"

.SS "time_t StudySession::m_timeEnded\fC [private]\fP"

.SS "time_t StudySession::m_timeStarted\fC [private]\fP"

.SS "\fBUser\fP StudySession::m_user\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
