.TH "app/src/todolist.cpp" 3StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/todolist.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./lib/todolist\&.h'\fP
.br
\fC#include <QVariant>\fP
.br
\fC#include <QVariantList>\fP
.br
\fC#include <QVariantMap>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <functional>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
