.TH "app/src/whiteboardwindow.cpp" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/src/whiteboardwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'lib/whiteboardwindow\&.h'\fP
.br
\fR#include 'ui_whiteboardwindow\&.h'\fP
.br
\fR#include 'lib/studysessionwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
