.TH "app/lib/whiteboardwindow.h" 3 "StudySphere" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/whiteboardwindow.h
.SH SYNOPSIS
.br
.PP
\fR#include <QApplication>\fP
.br
\fR#include <QMainWindow>\fP
.br
\fR#include <QMouseEvent>\fP
.br
\fR#include <QPainter>\fP
.br
\fR#include <QPen>\fP
.br
\fR#include <QPushButton>\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWhiteboardWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for StudySphere from the source code\&.
